version: "2.1"
volumes:
  speedtest-data:
  settings:
  vpnsettings:
  dashboard-data:
  adguardhome_work:
  adguardhome_conf:
  db:

services:
  speedtest:
    build: ./speedtest
    privileged: true
    restart: never
    volumes:
      - "speedtest-data:/data"
    network_mode: host
    labels:
      io.balena.features.supervisor-api: 1
  connector:
    image: balenablocks/connector
    restart: always
    labels:
      io.balena.features.balena-api: "1"
    privileged: true
  dashboard:
    restart: always
    build: ./dashboard
    ports:
      - "1928:80"
    volumes:
      - "dashboard-data:/data"
  influxdb:
    image: influxdb@sha256:73f876e0c3bd02900f829d4884f53fdfffd7098dd572406ba549eed955bf821f
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=balena
      - INFLUXDB_USER=balena
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DATA_DIR=/data
    volumes:
      - "speedtest-data:/data"
  mqtt:
    image: arm32v6/eclipse-mosquitto@sha256:ec3e1dbb9e198ff04d62c2d0f6eff74cad7438c7d080b89a28428fb96c8479c4
    ports:
      - "1883:1883"
    restart: always

  adguard:
    image: adguard/adguardhome:latest
    network_mode: host
    privileged: true
    volumes:
      - "adguardhome_work:/opt/adguardhome/work:rw"
      - "adguardhome_conf:/opt/adguardhome/conf:rw"
    command: --host 0.0.0.0 --port 80 --no-check-update --config /opt/adguardhome/conf/AdGuardHome.yaml

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname:latest
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: HomePi

  vpn:
    image: arm64v8/debian:latest
    privileged: true
    hostname: pritunl
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "1054:1054/tcp"
      - "1194:1194/tcp"
      - "1195:1195/udp"
      - "9700:9700/tcp"
    networks:
      vpn:
        ipv4_address: 192.168.1.88
    volumes:
      - "vpnsettings:/data"
  # 80/tcp pritunl web server http port (standalone mode)
  # 443/tcp pritunl web server https port (standalone and wireguard reverse-proxy mode)
  # 1194/tcp pritunl VPN service port
  # 1194/tcp pritunl OpenVPN service port
  # 1195/udp pritunl wireguard service port - No default in app, this is a suggestion only.
  # 9700/tcp pritunl web server http port (non-wireguard reverse-proxy mode)
  mongo:
    image: arm64v8/mongo:latest
    container_name: pritunldb
    hostname: pritunldb
    networks:
      vpn:
        ipv4_address: 192.168.1.90
    volumes:
      - "db:/data/db"

networks:
  vpn:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 255.255.255.0/24
          gateway: 192.168.1.254
